[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_tracks = "Hwvq856XGDLfHpTAWdPEYjhu9YwVEGN7jfYE6QC5FqQh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test2 = "npx ts-node client/client.ts"
